/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_team2363_helixtrajectory_HelixTrajectoryInterface */

#ifndef _Included_org_team2363_helixtrajectory_HelixTrajectoryInterface
#define _Included_org_team2363_helixtrajectory_HelixTrajectoryInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_team2363_helixtrajectory_HelixTrajectoryInterface
 * Method:    generateTrajectory
 * Signature: (Lorg/team2363/helixtrajectory/SwerveDrive;Lorg/team2363/helixtrajectory/Path;[Lorg/team2363/helixtrajectory/Obstacle;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_team2363_helixtrajectory_HelixTrajectoryInterface_generateTrajectory
  (JNIEnv *, jobject, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
