/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_team2363_helixtrajectory_HelixTrajectoryInterface */

#ifndef _Included_org_team2363_helixtrajectory_HelixTrajectoryInterface
#define _Included_org_team2363_helixtrajectory_HelixTrajectoryInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_team2363_helixtrajectory_HelixTrajectoryInterface
 * Method:    generateTrajectory
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_team2363_helixtrajectory_HelixTrajectoryInterface_generateTrajectory
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
