/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_team2363_helixtrajectory_OptimalTrajectoryGenerator */

#ifndef _Included_org_team2363_helixtrajectory_OptimalTrajectoryGenerator
#define _Included_org_team2363_helixtrajectory_OptimalTrajectoryGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_team2363_helixtrajectory_OptimalTrajectoryGenerator
 * Method:    generateHolonomicTrajectory
 * Signature: (Lorg/team2363/helixtrajectory/SwerveDrivetrain;Lorg/team2363/helixtrajectory/HolonomicPath;)Lorg/team2363/helixtrajectory/HolonomicTrajectory;
 */
JNIEXPORT jobject JNICALL Java_org_team2363_helixtrajectory_OptimalTrajectoryGenerator_generateHolonomicTrajectory
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
