/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_team2363_helixtrajectory_HolonomicTrajectoryGenerator */

#ifndef _Included_org_team2363_helixtrajectory_HolonomicTrajectoryGenerator
#define _Included_org_team2363_helixtrajectory_HolonomicTrajectoryGenerator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_team2363_helixtrajectory_HolonomicTrajectoryGenerator
 * Method:    generate
 * Signature: ()Lorg/team2363/helixtrajectory/HolonomicTrajectory;
 */
JNIEXPORT jobject JNICALL Java_org_team2363_helixtrajectory_HolonomicTrajectoryGenerator_generate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
