macro(installjavalibs)
  set(JAVA_LIB_TARGET_PATH ${CMAKE_CURRENT_SOURCE_DIR}/java/src/main/resources)
  if (${CMAKE_SYSTEM_NAME} MATCHES "MINGW" OR ${CMAKE_SYSTEM_NAME} MATCHES "MSYS" OR WIN32)
    if (CMAKE_SIZEOF_VOID_P EQUAL 8)
      set(JAVA_LIB_TARGET_PATH ${JAVA_LIB_TARGET_PATH}/windows/x86_64)
    elseif(CMAKE_SIZEOF_VOID_P EQUAL 4)
      set(JAVA_LIB_TARGET_PATH ${JAVA_LIB_TARGET_PATH}/windows/x86)
    endif()
  elseif (APPLE)
    set(JAVA_LIB_TARGET_PATH ${JAVA_LIB_TARGET_PATH}/osx/x86_64)
  elseif (UNIX)
    set(JAVA_LIB_TARGET_PATH ${JAVA_LIB_TARGET_PATH}/linux/x86_64)
  endif()
  message(STATUS "Path to use for java: ${JAVA_LIB_TARGET_PATH}")
  install(TARGETS TrajoptLib-java DESTINATION ${JAVA_LIB_TARGET_PATH})
endmacro()
